package org.radarcns.redcap.integration;

/*
 * Copyright 2017 King's College London
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonProperty;
import java.util.Objects;
import javax.validation.constraints.NotNull;
import org.apache.commons.lang3.builder.EqualsBuilder;
import org.apache.commons.lang3.builder.HashCodeBuilder;
import org.radarcns.redcap.util.RedCapInput;

/**
 * <p>Defines input parameters for updating RADAR Enrolment Instrument: a REDCap instrument
 * automatically created by REDCap during the integration process.</p>
 * <p>The instrument is composed by<ul>
 * <li>{@code record_id}: subject unique identifier within the REDCap project
 * <li>{@code subject_id}: RADAR subject identifier generated by the Management Portal
 * <li>{@code human_readable_id}: human readable identifier useful to visualise data. It
 *      should be the concatenation of<ul>
 *          <li>RADAR-CNS work package</li>
 *          <li>project identifier</li>
 *          <li>site</li>
 *          <li>REDCap record id</li></ul>
 * </ul></p>
 */
public class IntegrationData implements RedCapInput {

    /** Name of the REDCap form / instrument field where the RADAR Subject identifier has to be
     *  stored. */
    @JsonIgnore
    public static final String SUBJECT_ID_LABEL = "subject_id";

    /** Name of the REDCap form / instrument field where the Human Readable identifier has to be
     *  stored. */
    @JsonIgnore
    public static final String HUMAN_READABLE_ID_LABEL = "human_readable_id";

    /** REDCap Record identifier. */
    private final Integer record;

    /** REDCap Event name associated with the RECap form / instrument that will be updated. */
    @JsonProperty("redcap_event_name")
    private final String redcapEventName;

    /** REDCap filed name that will be updated. */
    @JsonProperty("field_name")
    private String fieldName;

    /** Value that will be written for the specified field name. */
    private String value;

    /**
     * Constructor.
     * @param record REDCap record identifier
     * @param event REDCap unique event identifier related to the instrument
     * @param field form field that has to be modified
     * @param value value that has to be written
     */
    public IntegrationData(@NotNull Integer record,@NotNull String event,@NotNull String field,
            @NotNull String value) {
        Objects.requireNonNull(record);
        Objects.requireNonNull(event);
        Objects.requireNonNull(field);
        Objects.requireNonNull(value);

        this.record = record;
        this.redcapEventName = event;
        this.fieldName = field;
        this.value = value;
    }

    /**
     * Returns the REDCap Record identifier.
     * @return {@link Integer} representing REDCap Record Identifier
     */
    @Override
    public Integer getRecord() {
        return record;
    }

    /**
     * Returns the REDCap Event name related to the update.
     * @return {@link String} representing REDCap Event name
     */
    public String getRedcapEventName() {
        return redcapEventName;
    }

    /**
     * Returns the field name that will be updated.
     * @return {@link String} representing field name
     */
    public String getFieldName() {
        return fieldName;
    }

    /**
     * Returns the value that will be written in REDCap.
     * @return {@link String} representing the value that will be written
     */
    public String getValue() {
        return value;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }

        if (!(obj instanceof IntegrationData)) {
            return false;
        }

        IntegrationData that = (IntegrationData) obj;

        return new EqualsBuilder()
            .append(record, that.record)
            .append(fieldName, that.fieldName)
            .append(value, that.value)
            .isEquals();
    }

    @Override
    public int hashCode() {
        return new HashCodeBuilder(17, 37)
            .append(record)
            .append(fieldName)
            .append(value)
            .toHashCode();
    }
}
